### ISSUE TITLE
Support http.route tag (and span naming) if possible

### ISSUE THREAD

**Issue by adriancole** [aio-libs/aiozipkin#115]
The "http.route" tag indicates a route expression like /users/:userId that corresponded with an http request. I'm not sure the aio framework has routing language or not, but if so, it will be nice.

https://zipkin.io/public/thrift/v1/zipkinCore.html#Const_HTTP_ROUTE

Note: the naming expression you use is the same as Brave, except it now uses templates and keywords for redirect or not found

https://github.com/openzipkin/brave/pull/602

**Comment by jettify** [comment]
There is language for routine like:
`/foo/bar/{name}`
`foo/bar/`
r`/foo/bar/{name:\d+}`
I just have not found good API to retrieve it, may be I missed something.

**Comment by jettify** [comment]
@asvetlov can you point me into right direction? For now I do not see better way than `request.match_info.route.get_info()['formatter'])`

**Comment by jettify** [comment]
As discussed special route should appear in aiohttp first https://github.com/aio-libs/aiohttp/issues/2968
