### ISSUE TITLE
Update all `secret: ` values in `.travis.yml`

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiozipkin#135]
Do like this:
```
REPO_NAME={{ YOUR_REPO_NAME }}
travis encrypt -r "aio-libs/${REPO_NAME}" --api-endpoint 'https://api.travis-ci.com/'
```

Ref: https://github.com/orgs/aio-libs/teams/admins/discussions/9

**Comment by webknjaz** [comment]
@jettify also remove old travis from web-hooks in repo settings.

**Comment by asvetlov** [comment]
Removed

**Comment by jettify** [comment]
Updated deploy config, now using `aio-libs-bot` user to upload releases
