### ISSUE TITLE
URL zipkin_address

### ISSUE THREAD

**Issue by dsantosfff** [aio-libs/aiozipkin#140]
Hi,

When creating a tracer we supply an URL, ex. https://traefik.company.com/zipkin.
In transport.py line 16 we have the fowlling code:
 `self._address = URL(address).with_path('/api/v2/spans')` it gives https://traefik.company.com/api/v2/spans

Has you can see it removes

> /zipkin

I suggest the fowling code
 `self._address = URL(address) / 'api/v2/spans'` it gives https://traefik.company.com/zipkin/api/v2/spans

Thank's for your attention.

**Comment by adriancole** [comment]
routinely we probably don't want to encourage the /zipkin prefix for the
api endpoint. it is defined as rooted under /api. the server mounts /zipkin
path for the UI (and does not accept POST under /zipkin)

**Comment by dsantosfff** [comment]
I put /zipkin as an example.
If a put `/tes` i still have the same probleme. 
I didn't mention but i the url is translated by traefik, that will Strip the PathPrefix (ex. /test)

**Comment by jettify** [comment]
I think it is good idea, would you like to create PR?

**Comment by dsantosfff** [comment]
@jettify 
When i try to push my branch i have this error:

> remote: Permission to aio-libs/aiozipkin.git denied to dsantosfff.

What can i do?

**Comment by asvetlov** [comment]
Please fork the project: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by dsantosfff** [comment]
@asvetlov Thank's nice tuto 

@jettify PR done.

**Comment by jettify** [comment]
New version released with the fix https://pypi.org/project/aiozipkin/0.3.0/
