### ISSUE TITLE
Allow for specifying full path to zipkin endpoint

### ISSUE THREAD

**Issue by deejay1** [aio-libs/aiozipkin#149]
Right now the zipkin address always has `api/v2/spans` appended to it, which doesn't allow for providing a full URL for the transport when the receiver requires a different URL (in our case it's a custom queue provider which then forwards the spans to proper collectors). Overriding that requires creation of a custom transport and `create()` function. 

This is somewhat related to #140

**Comment by jettify** [comment]
I see your point, this is a bit backward incompatible change, I guess better to do this sooner then later.

**Comment by adriancole** [comment]
this is helpful as there are an increasing large number of zipkin
compatible proxies, as well.. some of them are https and probably most are
rooted at /api/v2 but possibly not.

**Comment by jettify** [comment]
Fixed, new version released https://pypi.org/project/aiozipkin/0.4.0/
