### ISSUE TITLE
Tornado Instrumentation

### ISSUE THREAD

**Issue by nicholasamorim** [aio-libs/aiozipkin#202]
Hi, thanks for this project.

Is there any interest in a Tornado instrumentation? I'd love to implement it if there's interest and some pointers can be given on how to best do it.

**Comment by jettify** [comment]
Hi, I am not that familiar with tornado, but should be relatively easy to do, aiozipkin can work with any asyncio project. 

Idea is very simple write middleware for tornado where you create instance of tracer before request, start span there (set all info like IP address if available, URL, path, method etc), and finish span after request send (set here status code, payload size, etc). 

All instrumentation for aiohttp server is here:
https://github.com/aio-libs/aiozipkin/blob/3dbdd9e32127cb2b04d23881199243999e2fc4f4/aiozipkin/aiohttp_helpers.py#L39-L177
