### ISSUE TITLE
Add retries to send spans

### ISSUE THREAD

**Issue by konstantin-stepanov** [aio-libs/aiozipkin#204]
Maybe it's time to implement retries? 
TODO: https://github.com/aio-libs/aiozipkin/blob/master/aiozipkin/transport.py#L79

Also it would be great if user can set maximum batch size to send request
https://github.com/aio-libs/aiozipkin/blob/master/aiozipkin/transport.py#L58

I think that retries must be if client got aiohttp.ClientError or TimeoutError. Also need a limit on the number of attempts

**Comment by jettify** [comment]
Agreed, any help very appreciated.

**Comment by konstantin-stepanov** [comment]
May be I can help with it, but I don't know how to test it and how to make graceful shutdown

**Comment by jettify** [comment]
What do you mean by graceful shutdown?

Testing a bit tricky but doable, one can create simple mocking server with aiohttp that mimics zipkin server. Own mock server easy to control and simulate timeouts, 500 status codes etc.

**Comment by konstantin-stepanov** [comment]
I mean that when tracer is stopping it must send spans to zipkin, if they are not sent yet. But zipkin may not be available at this moment. What do we have to do in this case?

**Comment by jettify** [comment]
Thats relatively easy, try few times then drop spans. Spans are not critical data, loosing it is ok, since in most of the cases they are sampled anyway.

**Comment by jettify** [comment]
Implemented by #207
