### ISSUE TITLE
Unknown-service-name Jaegar v1 

### ISSUE THREAD

**Issue by maitham1** [aio-libs/aiozipkin#209]
Hi,

When using jaegar v1 api : 

> endpoint = az.create_endpoint('aiohttpServe', ipv4=host, port=port)
> jaegar = 'http://127.0.0.1:9411/api/v1/spans'
> tracer = await az.create(jaegar, endpoint, sample_rate=1.0)

I get unknown-service-name in jaegar.  Using 'http://127.0.0.1:9411/api/v2/spans' works fine. Anyone else experience this issue?

**Comment by jettify** [comment]
Hi, aiozipkin supports only v2 protocol.

**Comment by jettify** [comment]
Closing for now, feel free to reopen if  you have any other questions.
