### ISSUE TITLE
Span's context manager marks aiohttp.HTTPException as an error

### ISSUE THREAD

**Issue by asovchar** [aio-libs/aiozipkin#244]
aiohttp provides HTTPException, so the return values can be raised as exceptions.
The problem is that the context manager of the span.Span class handles them as a common exception and adds an error tag to the span.
Is there any way not to add this tag to HTTPSuccessful, HTTPRedirection and HTTPClientError?

**Comment by asovchar** [comment]
I've managed this by creating a middleware that catches HTTPExceptions and returns them as a return value, but this issue still occurs if I raise HTTPException from the context of the child span in handlers. It was also managed by a workaround, but I don't really like the way it is.

`
from aiohttp import web
from aiozipkin import Tracer
from aiozipkin.span import SpanAbc
from contextlib import contextmanager

@contextmanager
def f(tracer: Tracer, span: SpanAbc):
    child_span = tracer.new_child(span.context)
    child_span.start()
    try:
        yield child_span
    except web.HTTPServerError as e:
        child_span.finish(exception=e)
        raise
    except web.HTTPException:
        child_span.finish()
        raise
`

**Comment by jettify** [comment]
@asovchar good point, we can extend this part to handle `HTTPSuccessful` and others properly: 
https://github.com/aio-libs/aiozipkin/blob/9ab32dc50bf3e13d14d394e19dba882403414852/aiozipkin/aiohttp_helpers.py#L130-L150

would you like to submit PR with those changes?

**Comment by asovchar** [comment]
Yeah, I'd like to

But I think that extending this part of the code won't solve the issue. It will handle exceptions after the leave the handler, but child span's context manager will still mark raised exception as an error.
I think there has to be `AiohttpSpan` class that derives `Span` class, but has modified `__exit__` method in order to handle HTTPSuccessful and others correctly. But these will lead to changes in `Tracer` class in order to use `AiohttpSpan`.

What do you think about it?

**Comment by jettify** [comment]
Ah, I see your point.

Other option is to add extra parameter to the Tracer/Span classes, like `ignored_exception: Optinoal[List[Exception]]=None`, and if specified exception captured do not do `self.tag(ERROR, str(exception))`

**Comment by asovchar** [comment]
All changes are done
What about merging the PR?

**Comment by asovchar** [comment]
@jettify
