### ISSUE TITLE
aiohttp: Implement a list of ignored url/patterns

### ISSUE THREAD

**Issue by asyd** [aio-libs/aiozipkin#39]
Hi, 

i'm wondering if you're agree to provide an optional argument to `aiohttp_helpers` to define a list of url/patterns that should be ignored by the middleware? I use `aiozipkin` in APIs that provide healtcheck and I don't want to have trace for each healthcheck call (but I want a `sample_rate` set to 1)

Thanks

**Comment by jettify** [comment]
Make sense, would you like to create PR?

**Comment by asyd** [comment]
Sure.

**Comment by jettify** [comment]
Feature implemented in https://github.com/aio-libs/aiozipkin/pull/79

**Comment by asyd** [comment]
Ohh thanks to you @jettify !

**Comment by jettify** [comment]
You are welcome! Just in case here is complete example how to use this feature:

https://github.com/aio-libs/aiozipkin/blob/979b79cc60e9173d665f3b86d29bbcd9bc3fef44/examples/aiohttp_example.py#L1-L71
