### ISSUE TITLE
Support fastapi

### ISSUE THREAD

**Issue by sangkyunkim89** [aio-libs/aiozipkin#408]
dont use fastapi?

**Comment by Dreamsorcerer** [comment]
Sorry, your question does not make sense.

Did you mean that you have tried it with fastapi and it didn't work?

**Comment by sangkyunkim89** [comment]
That's right I tried to apply the module with fast api, but it doesn't work
It seems that only the aiohttp module is available, so maybe I don't know?


2021년 7월 15일 (목) 오전 1:40, Sam Bull ***@***.***>님이 작성:

**Comment by Dreamsorcerer** [comment]
I've not tried anything myself, but at a quick look, the `setup()` function is specifically for aiohttp.

You would probably need to create a new function for fastapi probably reimplementing everything in the aiohttp.py file:
https://github.com/aio-libs/aiozipkin/blob/master/aiozipkin/aiohttp_helpers.py#L177-L203

If you get it working, then feel free to make a PR so we can add support here.

**Comment by sangkyunkim89** [comment]
I tried to recreate it but gave up. I had to change the middleware
function as well as that function, so I've only been using python for
2 weeks...
Anyway, I asked a question just in case, but I can't help it, thanks
for the answer!


2021년 7월 15일 (목) 오전 1:54, Sam Bull ***@***.***>님이 작성:

**Comment by luminoso** [comment]
For fastapi integration check this: https://github.com/mchlvl/starlette-zipkin

**Comment by Dreamsorcerer** [comment]
That appears to actually use aiozipkin, so seems like a good approach. I'll mention it somewhere in the documentation.
