### ISSUE TITLE
Add support for jaeger-collector

### ISSUE THREAD

**Issue by konstantin-stepanov** [aio-libs/aiozipkin#49]
Jaeger-collector can accept zipkin spans, but in current implementation it does not working. It because there is no header `Content-Type: application/json` in the request and there may be nulls ​​in the values ​​of ip addresses

**Comment by adriancole** [comment]
you should probably raise a bug in jaeger as their http endpoint should be corrected to accomodate nulls or lack of content-type header. zipkin's default content-type on the post endpoint is json, and nulls are a simple json marshalling thing they can handle

**Comment by jettify** [comment]
Would you like to create PR, I am not familiar with jaeger spec to do this for now.

**Comment by acsnem** [comment]
Jaeger accepts spans on port 9411. On this port it accepts JSON or Thrift formats. Format recognition occurs by Content-Type header (see: https://jaeger.readthedocs.io/en/latest/deployment/). Therefore, transfer of this header is important for Jaeger.

I've not found the fact that zipkin should not accept null values in ip-addresses. But in the example of the data model on the official site there are no such values (see: https://zipkin.io/pages/data_model.html). In this example, there is nothing like: "ipv6": null. But I know that jaeger does not accept them.

Also, jaeger does not take tag values ​​in data types other than string. Therefore, you must do a forced typecasting.

**Comment by adriancole** [comment]
>
> Jaeger accepts spans on port 9411. On this port it accepts JSON or Thrift
> formats. Format recognition occurs by Content-Type header (see:
> https://jaeger.readthedocs.io/en/latest/deployment/). Therefore, transfer
> of this header is important for Jaeger.
>
right but just saying jaeger's emulator could be fixed to have a default
content-type. Now, we have to send a header not needed in zipkin. It is ok,
but you should know that zipkin actually decides what the rules are for its
endpoint/

> I've not found the fact that zipkin should not accept null values in
> ip-addresses. But in the example of the data model on the official site
> there are no such values (see: https://zipkin.io/pages/data_model.html).
> In this example, there is nothing like: "ipv6": null. But I know that
> jaeger does not accept them.
>
https://zipkin.io/zipkin-api/#/default/post_spans is the official site (ps
I wrote most of this api doc). "ipv6": null is a json condition and another
client will break jaeger. It is fine to let something else break them, just
saying usually best is to report bugs.

> Also, jaeger does not take tag values ​​in data types other than string.
> Therefore, you must do a forced typecasting.
>
This part is definitely correct. tags are string->string

**Comment by jettify** [comment]
FYI I added test case with jaeger server https://github.com/aio-libs/aiozipkin/pull/55
