### ISSUE TITLE
Record.annotate() behavior

### ISSUE THREAD

**Issue by konstantin-stepanov** [aio-libs/aiozipkin#57]
Is it correct behavior for method `Record.annotate`?

```
def annotate(self, value, ts):
        if value == CLIENT_SEND:
            self.kind(CLIENT)
            self._timestamp = ts
        elif value == SERVER_RECEIVED:
            self.kind(SERVER)
            self._timestamp = ts
        elif value == CLIENT_RECEIVED:
            self.kind(CLIENT)
            self.finish(ts)
        elif value == SERVER_SEND:
            self.kind(SERVER)
            self.finish(ts)
        else:
            v = {'value': value, 'timestamp': int(ts)}
            self._annotations.append(v)
        return self
```

What if user want to send `"cs"` value as annotation, like `span.annotate('cs')`? And user want to see it as annotation, not as timestamp correction.
For example, I log every request body of inbound requests in my API and some one sent `sr` in request body. In this case, I will not see anything in the annotation.
It can be any other example in which we store some random data as an annotation.

If you want to keep the current behavior, you can make the value of `CLIENT_SEND` (and others) as instance of the class inherited from `str`. And in the `annotate` method check for `isinstance`, not for equivalence

**Comment by jettify** [comment]
I followed logic from zipkin brave client:
https://github.com/openzipkin/brave/blob/c5e164a06ba4f909ad0ce4700e97ef16f5b5ed15/brave/src/main/java/brave/internal/recorder/MutableSpan.java#L57-L72
`sr`, `cs` and friends a sort of reserved values in zipkin as far as I can tell. 

But you are right, probably Enum should be used to distinguish those.

**Comment by adriancole** [comment]
ideally we stop using the bookend annotations and transition to span.kind which clarifies span.timestamp and duration. Special casing around "cs" etc mostly exists for old libraries

**Comment by adriancole** [comment]
what i mean is that in the brave code mentioned, this was a bridge for the "brave 3" style apis which would send these. Recent apis no longer do this.

**Comment by jettify** [comment]
@adriancole thanks for clarification! Then we can drop that logic safely, simpler better :)

**Comment by jettify** [comment]
@konstantin-stepanov would you like to create PR? Remove indicated logic and drop related test cases?

**Comment by konstantin-stepanov** [comment]
I will try to create PR.

Also I found one more exception. If you pass not a string or a number value to the `span.annotate` then zipkin will respond with an HTTP 400 error with body "Cannot decode spans"

**Comment by jettify** [comment]
fixed in https://github.com/aio-libs/aiozipkin/pull/58
