### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by konstantin-stepanov** [aio-libs/aiozipkin#73]
To quickly reproduce the problem, you need to reduce the value of the argument `send_inteval` to a very small value and see what happens with the memory.

Here is an example of code for reproduce a memory leak:

```python
import gc
import asyncio
import aiozipkin as az
from functools import partial
from pympler import muppy, summary


def mem_test(loop):
    gc.collect()
    try:
        all_objects = muppy.get_objects()
        sum = summary.summarize(all_objects)
        summary.print_(sum)
    finally:
        loop.call_later(1, partial(mem_test, loop))


async def run():
    zipkin_address = 'http://127.0.0.1:9411'
    endpoint = az.create_endpoint('minimal_example', ipv4='127.0.0.1')

    tracer = az.create(zipkin_address, endpoint, sample_rate=1.0,
                       send_inteval=0.001)

    await asyncio.sleep(60)

    await tracer.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.call_soon(partial(mem_test, loop))
    try:
        loop.run_until_complete(run())
    except KeyboardInterrupt:
        pass
```

The problem in function `_wait` of `Transport`.

It's difficult for me to explain this behavior, but replacing the function `asyncio.as_completed` to `asyncio.wait` solves this problem

```python
    async def _wait(self) -> None:
        self._timer = asyncio.ensure_future(
            asyncio.sleep(self._send_interval, loop=self._loop),
            loop=self._loop)

        await asyncio.wait([self._timer, self._ender], loop=self._loop,
                           return_when=asyncio.FIRST_COMPLETED)
```

**Comment by jettify** [comment]
Good catch, `asyncio.wait` should work too. I am still not sure why memory leaks, `as_completed` has a bit more complicated implementation with internal queue, probably bunch of objects stuck there.  

Would you like to create PR?

**Comment by konstantin-stepanov** [comment]
Yes. I'll create it

**Comment by jettify** [comment]
Thanks a lot!

**Comment by jettify** [comment]
added test case here https://github.com/aio-libs/aiozipkin/pull/75

**Comment by jettify** [comment]
New version deployed to PyPI https://pypi.python.org/pypi/aiozipkin/0.0.1b8
