### ISSUE TITLE
the example may need to change

### ISSUE THREAD

**Issue by jiamo** [aio-libs/aiozipkin#90]
This example 

```
await tracer.close()
import asyncio
import aiozipkin as az


async def run():
    # setup zipkin client
    zipkin_address = 'http://127.0.0.1:9411'
    endpoint = az.create_endpoint(
        'simple_service', ipv4='127.0.0.1', port=8080)

    # creates tracer object that traces all calls, if you want sample
    # only 50% just set sample_rate=0.5
    tracer = az.create(zipkin_address, endpoint, sample_rate=1.0)

    # create and setup new trace
    with tracer.new_trace(sampled=True) as span:
        span.name('root_span')
        span.tag('span_type', 'root')
        span.kind(az.CLIENT)
        span.annotate('SELECT * FROM')
        # imitate long SQL query
        await asyncio.sleep(0.1)
        span.annotate('start end sql')

        # create child span
        with tracer.new_child(span.context) as nested_span:
            nested_span.name('nested_span_1')
            nested_span.kind(az.CLIENT)
            nested_span.tag('span_type', 'inner1')
            nested_span.remote_endpoint('remote_service_1')
            await asyncio.sleep(0.01)

        # create other child span
        with tracer.new_child(span.context) as nested_span:
            nested_span.name('nested_span_2')
            nested_span.kind(az.CLIENT)
            nested_span.remote_endpoint('remote_service_2')
            nested_span.tag('span_type', 'inner2')
            await asyncio.sleep(0.01)

        await asyncio.sleep(30)
        await tracer.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run())

```

The `await tracer.close()` may be need put outside the `with`. Otherwise the root span can't be sent to collecter.

**Comment by jiamo** [comment]
another question:  Can we only send data only the time is bigger than `100ms`.  Because there are so many request and I only care about the slow request. so the span with little delay(such as `1ms`) may don't need to send to the collector (which is also a service need resource to hold all the request)

**Comment by konstantin-stepanov** [comment]
Hi. For such specific tasks it is better to override the transport class i think. But implementation of the filtering of the spans by their parameters seems to me a good idea. 
It can be combined with #39.
@jettify what do you think about this?

**Comment by jettify** [comment]
Good catch! I have not updated this example, after implementing transport more properly, also agree on `asyncio.sleep` should be removed. 

@jiamo would you like to create PR with fix?

**Comment by jettify** [comment]
As for question, I am not sure how to implement time filtering, consider following scenario:
We have 3 chained spans with times 1ms, 1ms and 101ms, we leave only third span due to filter, as result we also loose important information a full chain of calls that leaded to this particular span. 

If you want to see response time of one particular endpoint, than other statistics and monitoring tools are more suitable (like https://github.com/graphite-project). Value of distributed tracing in seeing chain of calls and all interactions with other services.

**Comment by jiamo** [comment]
In this case `We have 3 chained spans with times 1ms, 1ms and 101ms`  What I wish is to collect them all because the `total cast = 1 + 1 + 101` is big. (I don't looked into the source code. If it send data to collector at the `close` (will always called my `on_response` middleware in sanic) Then the filter is meaningful.

**Comment by jettify** [comment]
Sorry it is not possible on client side, since each span could be generated
on different service on completly different machine. Your best bet is to
talk to zipkin server people, only there it is possible to see aggregated
data.

Anyway, in zipkin ui you can fetch longest traces for selected period of
time.

**Comment by jettify** [comment]
fixed in https://github.com/aio-libs/aiozipkin/commit/326e966ad61b0aa56cb18d5f7479e5f378787bbe

**Comment by jettify** [comment]
@konstantin-stepanov what do you think about context manger API around `az.create`?
```python
async with az.create(zipkin_address, endpoint, sample_rate=1.0) as tracer
    with tracer.new_trace(sampled=True) as span:
        span.name('root_span')
```
I just wondering if it is useful outside test...

**Comment by konstantin-stepanov** [comment]
I like this idea. This simplifies the code and it looks more readable.

As for useful, it depends on applicatuon architecture. I think It will be perfect in MVP

**Comment by jettify** [comment]
Create issue to track this idea https://github.com/aio-libs/aiozipkin/issues/99
