### ISSUE TITLE
Remove Namedtuple use

### ISSUE THREAD

**Issue by yunstanford** [aio-libs/aiozipkin#93]
Namedtuple is slow and confusing to use. 

might give attrs a try. http://www.attrs.org/en/stable/why.html#namedtuples

**Comment by jettify** [comment]
I like `attrs`, but in case of `aiozipkin` I do not see much benefit, we do not use `namedtuples` heavily. Exposed tuples to users (like TraceContext or Endpoint) are readonly, and have little value to user. Also `attrs` is extra dependency for  case when `namedtuples` works perfectly fine.

From other side next major version of `aiohttp` will use `attrs` internally, so my last argument will be not valid, at that point we can revisit usage of `namedtuples`.

**Comment by jettify** [comment]
FYI `aiozipkin` now works only with `aiohttp>=3.0.0` so `attars` already present.

**Comment by jettify** [comment]
Closing for now.
