### ISSUE TITLE
Implement async context manager API for az.create

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiozipkin#99]
1) `az.create` should be coroutine if at some point we decide to include rabbit/kafka/other integration, it will be very essential. From other side the is breaking change, better to do this earlier.

2) Context manager API should look like:
```python
async with az.create(zipkin_address, endpoint, sample_rate=1.0) as tracer
    with tracer.new_trace(sampled=True) as span:
        span.name('root_span')
```
3)  Old approach should work also:
```python
tracer = await az.create(zipkin_address, endpoint, sample_rate=1.0)
await tracer.close()
```

**Comment by adriancole** [comment]
So in this case context manager is not just making the span visible (in
context) but also handling lifecycle (finishing a span)? If so, I noticed
some libraries having multiple places where it is needed to make a span
visible, but where to close the span is usually one or two places. I
suppose I suggest mentioning that this does both things (or avail an api to
just place a span in context and layer over that)

If I sound nonsense it could be that I misunderstand the library, so dont
get too distracted if that is the case.

**Comment by jettify** [comment]
This context manager controls lifespan of `Tracer` object and responsible to finalize it once code execution over out of context (close network connections). During finalization we send all accumulated spans to the server.

**Comment by jettify** [comment]
fixed in https://github.com/aio-libs/aiozipkin/pull/114
